# name: This field specifies the name of your project.
# It's a unique identifier and should not contain spaces or special characters.
name: flutter_reviewer_main

# description: You can provide a brief description of your project to give others an idea of what it's about.
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

#  Dart Version Use
environment:
  # indicate that your project works with Flutter 3.5.3 or higher but not version 4.0.0.
  sdk: '>=3.5.3 <4.0.0'  # Dart SDK Version
  flutter: '>=3.24.3'  # Flutter SDK Version

#  Flutter 3.24.3 • channel stable • https://github.com/flutter/flutter.git
#  Framework • revision 2663184aa7 (31 hours ago) • 2024-09-11 16:27:48 -0500
#  Engine • revision 36335019a8
#  Tools • Dart 3.5.3 • DevTools 2.37.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter: # Required for every Flutter project
    sdk: flutter # Required for every Flutter project
  flutter_localizations: # Required to enable localization
    sdk: flutter         # Required to enable localization

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: any # Only required if you use Cupertino (iOS style) icons
  provider: any
  tuple: any
  device_preview: any
  feedback: any

  flutter_glow: any
  flutter_animate: any
  gap: any
  cached_network_image: any
  popover: any
  get: any
  image_picker: any
  flutter_svg: any
  go_router: any
  fl_chart: any
  google_fonts: any
  http: any
  flutter_highlight: any
  flutter_speed_dial: any
  selectable: any
  url_launcher: any
  string_scanner: any
  intl: any
  flutter_cache_manager: any # 3.3.2 https://pub.dev/packages/flutter_cache_manager
  flutter_emoji: any # 2.5.1 https://pub.dev/packages/flutter_emoji
  share_plus: any # 9.0.0 https://pub.dev/packages/share_plus
  file_picker: any # https://pub.dev/packages/file_picker
  flutter_localization: any # ^0.2.1 https://pub.dev/packages/flutter_localization
  characters: any # ^1.3.0  https://pub.dev/packages/characters
  connectivity_plus: any # ^6.0.4 https://pub.dev/packages/connectivity_plus
  shimmer_animation: any # ^2.2.1 https://pub.dev/packages/shimmer_animation
  firebase_auth: any # ^4.16.0 #https://pub.dev/packages/firebase_auth
  firebase_core: any # ^2.24.2 https://pub.dev/packages/firebase_core
  fluttertoast: any # ^8.2.8 https://pub.dev/packages/fluttertoast
  shared_preferences: any # ^2.3.2 https://pub.dev/packages/shared_preferences
  mix: any # ^1.4.6 https://pub.dev/packages/mix
  text_marquee: any
  #calendar_date_picker2: any # ^1.1.7 https://pub.dev/packages/calendar_date_picker2/install


dev_dependencies:
  flutter_test:
    sdk: flutter # Required for a Flutter project that includes tests

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/instagram_bottom_navigation_bar/assets/vectors/
    - assets/instagram_bottom_navigation_bar/assets/images/
    - assets/
    - assets/deep_quiz_img.png
    # Include a single source code file:
    # Include all files under a subfoler by adding trailing "/":
    - lib/template/

    - lang/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PingFangHK
      fonts:
        - asset: assets/fonts/PingFangHK-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Hipsters
      fonts:
        - asset: assets/fonts/hopsters.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  # Stable Package

#  flutter_reviewer_main 1.0.0+1
#  ├── cached_network_image 3.3.1
#  │   ├── cached_network_image_platform_interface 4.0.0
#  │   │   ├── flutter...
#  │   │   └── flutter_cache_manager...
#  │   ├── cached_network_image_web 1.2.0
#  │   │   ├── cached_network_image_platform_interface...
#  │   │   ├── flutter...
#  │   │   └── flutter_cache_manager...
#  │   ├── octo_image 2.0.0
#  ├── cupertino_icons 1.0.8
#  ├── device_preview 1.2.0
#  │   ├── device_frame 1.2.0
#  │   │   ├── flutter...
#  │   │   └── freezed_annotation...
#  │   ├── freezed_annotation 2.4.1
#  │   │   ├── collection...
#  │   │   ├── json_annotation...
#  │   │   └── meta...
#  │   ├── json_annotation 4.9.0
#  │   │   └── meta...
#  │   ├── shared_preferences 2.2.3
#  │   │   ├── shared_preferences_android 2.2.3
#  │   │   │   ├── flutter...
#  │   │   │   └── shared_preferences_platform_interface...
#  │   │   ├── shared_preferences_foundation 2.4.0
#  │   │   │   ├── flutter...
#  │   │   │   └── shared_preferences_platform_interface...
#  │   │   ├── shared_preferences_linux 2.3.2
#  │   │   │   ├── file...
#  │   │   │   ├── flutter...
#  │   │   │   ├── path...
#  │   │   │   ├── path_provider_linux...
#  │   │   │   ├── path_provider_platform_interface...
#  │   │   │   └── shared_preferences_platform_interface...
#  │   │   ├── shared_preferences_platform_interface 2.3.2
#  │   │   │   ├── flutter...
#  │   │   │   └── plugin_platform_interface...
#  │   │   ├── shared_preferences_web 2.3.0
#  │   │   │   ├── flutter...
#  │   │   │   ├── flutter_web_plugins...
#  │   │   │   ├── shared_preferences_platform_interface...
#  │   │   │   └── web...
#  │   │   ├── shared_preferences_windows 2.3.2
#  │   │   │   ├── file...
#  │   │   │   ├── flutter...
#  │   │   │   ├── path...
#  │   │   │   ├── path_provider_platform_interface...
#  │   │   │   ├── path_provider_windows...
#  │   │   │   └── shared_preferences_platform_interface...
#  │   │   └── flutter...
#  │   ├── collection...
#  │   ├── flutter...
#  │   ├── flutter_localizations...
#  │   └── provider...
#  ├── feedback 3.1.0
#  │   ├── flutter...
#  │   └── flutter_localizations...
#  ├── fl_chart 0.68.0
#  │   ├── equatable 2.0.5
#  │   │   ├── collection...
#  │   │   └── meta...
#  │   └── flutter...
#  ├── flutter 0.0.0
#  │   ├── characters 1.3.0
#  │   ├── collection 1.18.0
#  │   ├── material_color_utilities 0.8.0
#  │   │   └── collection...
#  │   ├── meta 1.12.0
#  │   ├── sky_engine 0.0.99
#  │   └── vector_math 2.1.4
#  ├── flutter_animate 4.5.0
#  │   ├── flutter_shaders 0.1.2
#  │   │   ├── flutter...
#  │   │   └── vector_math...
#  │   └── flutter...
#  ├── flutter_cache_manager 3.3.2
#  │   ├── file 7.0.0
#  │   │   ├── meta...
#  │   │   └── path...
#  │   ├── rxdart 0.27.7
#  │   ├── sqflite 2.3.3+1
#  │   │   ├── sqflite_common 2.5.4
#  │   │   │   ├── synchronized 3.1.0+1
#  │   │   │   ├── meta...
#  │   │   │   └── path...
#  │   │   ├── flutter...
#  │   │   └── path...
#  │   ├── uuid 4.4.0
#  │   │   ├── fixnum 1.1.0
#  │   │   ├── sprintf 7.0.0
#  │   │   ├── crypto...
#  │   │   └── meta...
#  │   ├── clock...
#  │   ├── collection...
#  │   ├── flutter...
#  │   ├── http...
#  │   ├── path...
#  │   └── path_provider...
#  ├── flutter_emoji 2.5.1
#  ├── flutter_glow 0.3.0
#  ├── flutter_highlight 0.7.0
#  │   ├── highlight 0.7.0
#  │   │   └── collection...
#  │   └── flutter...
#  ├── flutter_lints 4.0.0
#  │   └── lints 4.0.0
#  ├── flutter_localizations 0.0.0
#  │   ├── clock 1.1.1
#  │   ├── path 1.9.0
#  │   ├── characters...
#  │   ├── collection...
#  │   ├── flutter...
#  │   ├── intl...
#  │   ├── material_color_utilities...
#  │   ├── meta...
#  │   └── vector_math...
#  ├── flutter_speed_dial 7.0.0
#  │   └── flutter...
#  ├── flutter_svg 2.0.10+1
#  │   ├── vector_graphics 1.1.11+1
#  │   │   ├── flutter...
#  │   │   ├── http...
#  │   │   └── vector_graphics_codec...
#  │   ├── vector_graphics_codec 1.1.11+1
#  │   ├── vector_graphics_compiler 1.1.11+1
#  │   │   ├── args 2.5.0
#  │   │   ├── path_parsing 1.0.1
#  │   │   │   ├── meta...
#  │   │   │   └── vector_math...
#  │   │   ├── xml 6.5.0
#  │   │   │   ├── petitparser 6.0.2
#  │   │   │   │   └── meta...
#  │   │   │   ├── collection...
#  │   │   │   └── meta...
#  │   │   ├── meta...
#  │   │   ├── path...
#  │   │   └── vector_graphics_codec...
#  │   ├── flutter...
#  │   └── http...
#  ├── flutter_test 0.0.0
#  │   ├── boolean_selector 2.1.1
#  │   │   ├── source_span...
#  │   │   └── string_scanner...
#  │   ├── fake_async 1.3.1
#  │   │   ├── clock...
#  │   │   └── collection...
#  │   ├── leak_tracker 10.0.4
#  │   │   ├── clock...
#  │   │   ├── collection...
#  │   │   ├── meta...
#  │   │   ├── path...
#  │   │   └── vm_service...
#  │   ├── leak_tracker_flutter_testing 3.0.3
#  │   │   ├── flutter...
#  │   │   ├── leak_tracker...
#  │   │   ├── leak_tracker_testing...
#  │   │   ├── matcher...
#  │   │   └── meta...
#  │   ├── leak_tracker_testing 3.0.1
#  │   │   ├── leak_tracker...
#  │   │   ├── matcher...
#  │   │   └── meta...
#  │   ├── matcher 0.12.16+1
#  │   │   ├── async...
#  │   │   ├── meta...
#  │   │   ├── stack_trace...
#  │   │   ├── term_glyph...
#  │   │   └── test_api...
#  │   ├── stack_trace 1.11.1
#  │   │   └── path...
#  │   ├── stream_channel 2.1.2
#  │   │   └── async...
#  │   ├── term_glyph 1.2.1
#  │   ├── test_api 0.7.0
#  │   │   ├── async...
#  │   │   ├── boolean_selector...
#  │   │   ├── collection...
#  │   │   ├── meta...
#  │   │   ├── source_span...
#  │   │   ├── stack_trace...
#  │   │   ├── stream_channel...
#  │   │   ├── string_scanner...
#  │   │   └── term_glyph...
#  │   ├── vm_service 14.2.1
#  │   ├── async...
#  │   ├── characters...
#  │   ├── clock...
#  │   ├── collection...
#  │   ├── flutter...
#  │   ├── material_color_utilities...
#  │   ├── meta...
#  │   ├── path...
#  │   ├── source_span...
#  │   ├── string_scanner...
#  │   └── vector_math...
#  ├── gap 3.0.1
#  │   └── flutter...
#  ├── get 4.6.6
#  │   └── flutter...
#  ├── go_router 14.1.4
#  │   ├── flutter_web_plugins 0.0.0
#  │   │   ├── characters...
#  │   │   ├── collection...
#  │   │   ├── flutter...
#  │   │   ├── material_color_utilities...
#  │   │   ├── meta...
#  │   │   └── vector_math...
#  │   ├── logging 1.2.0
#  │   ├── collection...
#  │   ├── flutter...
#  │   └── meta...
#  ├── google_fonts 6.2.1
#  │   ├── crypto 3.0.3
#  │   │   └── typed_data 1.3.2
#  │   │       └── collection...
#  │   ├── path_provider 2.1.3
#  │   │   ├── path_provider_android 2.2.5
#  │   │   │   ├── flutter...
#  │   │   │   └── path_provider_platform_interface...
#  │   │   ├── path_provider_foundation 2.4.0
#  │   │   │   ├── flutter...
#  │   │   │   └── path_provider_platform_interface...
#  │   │   ├── path_provider_linux 2.2.1
#  │   │   │   ├── ffi 2.1.2
#  │   │   │   ├── xdg_directories 1.0.4
#  │   │   │   │   ├── meta...
#  │   │   │   │   └── path...
#  │   │   │   ├── flutter...
#  │   │   │   ├── path...
#  │   │   │   └── path_provider_platform_interface...
#  │   │   ├── path_provider_platform_interface 2.1.2
#  │   │   │   ├── platform 3.1.4
#  │   │   │   ├── flutter...
#  │   │   │   └── plugin_platform_interface...
#  │   │   ├── path_provider_windows 2.2.1
#  │   │   │   ├── win32 5.5.1
#  │   │   │   │   └── ffi...
#  │   │   │   ├── ffi...
#  │   │   │   ├── flutter...
#  │   │   │   ├── path...
#  │   │   │   └── path_provider_platform_interface...
#  │   │   └── flutter...
#  │   ├── flutter...
#  │   └── http...
#  ├── http 1.2.1
#  │   ├── async 2.11.0
#  │   │   ├── collection...
#  │   │   └── meta...
#  │   ├── http_parser 4.0.2
#  │   │   ├── collection...
#  │   │   ├── source_span...
#  │   │   ├── string_scanner...
#  │   │   └── typed_data...
#  │   ├── web 0.5.1
#  │   └── meta...
#  ├── image_picker 1.1.1
#  │   ├── image_picker_android 0.8.12+2
#  │   │   ├── flutter_plugin_android_lifecycle 2.0.20
#  │   │   │   └── flutter...
#  │   │   ├── flutter...
#  │   │   └── image_picker_platform_interface...
#  │   ├── image_picker_for_web 3.0.4
#  │   │   ├── mime 1.0.5
#  │   │   ├── flutter...
#  │   │   ├── flutter_web_plugins...
#  │   │   ├── image_picker_platform_interface...
#  │   │   └── web...
#  │   ├── image_picker_ios 0.8.11+2
#  │   │   ├── flutter...
#  │   │   └── image_picker_platform_interface...
#  │   ├── image_picker_linux 0.2.1+1
#  │   │   ├── file_selector_linux 0.9.2+1
#  │   │   │   ├── cross_file...
#  │   │   │   ├── file_selector_platform_interface...
#  │   │   │   └── flutter...
#  │   │   ├── file_selector_platform_interface 2.6.2
#  │   │   │   ├── cross_file...
#  │   │   │   ├── flutter...
#  │   │   │   ├── http...
#  │   │   │   └── plugin_platform_interface...
#  │   │   ├── flutter...
#  │   │   └── image_picker_platform_interface...
#  │   ├── image_picker_macos 0.2.1+1
#  │   │   ├── file_selector_macos 0.9.4
#  │   │   │   ├── cross_file...
#  │   │   │   ├── file_selector_platform_interface...
#  │   │   │   └── flutter...
#  │   │   ├── file_selector_platform_interface...
#  │   │   ├── flutter...
#  │   │   └── image_picker_platform_interface...
#  │   ├── image_picker_platform_interface 2.10.0
#  │   │   ├── cross_file 0.3.4+1
#  │   │   │   ├── meta...
#  │   │   │   └── web...
#  │   │   ├── plugin_platform_interface 2.1.8
#  │   │   │   └── meta...
#  │   │   ├── flutter...
#  │   │   └── http...
#  │   ├── image_picker_windows 0.2.1+1
#  │   │   ├── file_selector_windows 0.9.3+1
#  │   │   │   ├── cross_file...
#  │   │   │   ├── file_selector_platform_interface...
#  │   │   │   └── flutter...
#  │   │   ├── file_selector_platform_interface...
#  │   │   ├── flutter...
#  │   │   └── image_picker_platform_interface...
#  │   └── flutter...
#  ├── intl 0.19.0
#  │   ├── clock...
#  │   ├── meta...
#  │   └── path...
#  ├── popover 0.3.0+1
#  │   └── flutter...
#  ├── provider 6.1.2
#  │   ├── nested 1.0.0
#  │   │   └── flutter...
#  │   ├── collection...
#  │   └── flutter...
#  ├── selectable 0.3.1
#  │   ├── float_column 2.1.5
#  │   │   └── flutter...
#  │   ├── characters...
#  │   ├── collection...
#  │   ├── equatable...
#  │   ├── flutter...
#  │   └── url_launcher...
#  ├── string_scanner 1.2.0
#  │   └── source_span 1.10.0
#  │       ├── collection...
#  │       ├── path...
#  │       └── term_glyph...
#  ├── tuple 2.0.2
#  └── url_launcher 6.2.6
#  ├── url_launcher_android 6.3.3
#  │   ├── flutter...
#  │   └── url_launcher_platform_interface...
#  ├── url_launcher_ios 6.3.0
#  │   ├── flutter...
#  │   └── url_launcher_platform_interface...
#  ├── url_launcher_linux 3.1.1
#  │   ├── flutter...
#  │   └── url_launcher_platform_interface...
#  ├── url_launcher_macos 3.2.0
#  │   ├── flutter...
#  │   └── url_launcher_platform_interface...
#  ├── url_launcher_platform_interface 2.3.2
#  │   ├── flutter...
#  │   └── plugin_platform_interface...
#  ├── url_launcher_web 2.3.1
#  │   ├── flutter...
#  │   ├── flutter_web_plugins...
#  │   ├── url_launcher_platform_interface...
#  │   └── web...
#  ├── url_launcher_windows 3.1.1
#  │   ├── flutter...
#  │   └── url_launcher_platform_interface...
#  └── flutter...